package proxmox

// This file holds the ONE place in moxy where an API token secret is turned
// back into plain text. Everything else — configuration, logs, errors, the
// JSON of /api/overview — sees only the redacted form of config.Secret.
//
// Two rules apply to anything added here:
//
//   - never log or format an *http.Request, and never use
//     httputil.DumpRequestOut: both print the Authorization header verbatim;
//   - never log or keep an *http.Response either, before its Request field has
//     been cleared: http.Transport fills that field with the request it sent,
//     which carries the same header. attempt clears it as soon as Do returns;
//   - never copy the revealed secret into a field, a closure or an error. It
//     lives on the stack for the duration of one header assignment.

import (
	"errors"
	"net/http"

	"github.com/dmajorel/moxy/apps/api/internal/config"
)

const (
	// authHeader is the header carrying the Proxmox API token.
	authHeader = "Authorization"
	// authScheme is the Proxmox token scheme. The full value is
	// "PVEAPIToken=<user>@<realm>!<tokenid>=<secret>", the secret being a
	// UUID generated by PVE when the token is created.
	authScheme = "PVEAPIToken="
)

// errNilRequest guards the RoundTripper contract; it cannot happen through the
// Client, only through a direct misuse of the transport.
var errNilRequest = errors.New("proxmox: nil request")

// authTransport is an http.RoundTripper that authenticates every request with
// a Proxmox API token. It is the only holder of a cluster secret, and the only
// legitimate caller of config.Secret.Reveal.
//
// The fields are EXPORTED on purpose, unexported-looking as the type itself
// is: fmt reaches a Formatter or a Stringer only through a field it can
// Interface(), which excludes unexported ones, and prints what it cannot reach
// by reflection instead. config.Secret now holds its value behind a pointer,
// so reflection finds an address rather than the token and this is no longer
// the only thing standing between %+v and the secret — but it stays the clear
// habit. See config/secret.go.
type authTransport struct {
	// Base does the actual work. A nil Base means http.DefaultTransport,
	// which the Client never relies on: it always supplies its own, carrying
	// the TLS policy of the cluster.
	Base http.RoundTripper
	// TokenID is the non-sensitive half of the token, "user@realm!tokenid".
	TokenID string
	// Secret is the sensitive half. It is revealed once per request, into a
	// header value that is never retained.
	Secret config.Secret
}

// RoundTrip implements http.RoundTripper.
//
// The request is CLONED before the header is set. A RoundTripper must not
// modify the request it is handed: http.Client may still read it (for a
// redirect, a retry or an error message), and mutating a shared *http.Request
// is the classic way to make an Authorization header appear where it was never
// meant to go.
func (t *authTransport) RoundTrip(r *http.Request) (*http.Response, error) {
	if r == nil {
		return nil, errNilRequest
	}
	clone := r.Clone(r.Context())
	if clone.Header == nil {
		clone.Header = make(http.Header)
	}
	clone.Header.Set(authHeader, authScheme+t.TokenID+"="+t.Secret.Reveal())

	base := t.Base
	if base == nil {
		base = http.DefaultTransport
	}
	return base.RoundTrip(clone)
}
